site_name: Ezio's tech blog
repo_url: https://github.com/CLQuantizer/eztech
extra_css:
  - stylesheets/extra.css

theme:
    name: material
    palette:
      primary: pink

nav:
  - Blog:
    - blog/index.md
    - blog/posts/Rust.md

plugins:
  - blog:
      enabled: !ENV [CI, false]

plugins:
  - blog:
      post_url_date_format: yyyy/MM/dd

