site_name: whatever works

repo_url: https://github.com/CLQuantizer/eztech
extra_css:
  - stylesheets/extra.css

theme:
    name: material
    palette:
      primary: pink

plugins:
  - blog:
    enabled: !ENV [CI, false]
    blog_dir: path/to/folder
    post_date_format: full


nav:
  - Blog:
    - blog/index.md 



