site_name: Chez Ezio
repo_url: https://github.com/CLQuantizer/ezblog
# extra_css:
#   - stylesheets/extra.css

theme:
    logo: assets/logo.png
    name: material
    palette:
      # Palette toggle for light mode
      - scheme: default
        toggle:
          icon: material/brightness-7 
          name: Switch to dark mode

      # Palette toggle for dark mode
      - scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode

nav:
  - blog/Rust.md
  - Java:  
    - blog/java/post_construct.md
  - Dinosaurs:
    - blog/dinosaurs/core_dump.md
  - Poetry:
    - blog/poetry/Sparks.md
  - Rust_memory:
    - blog/Rust_memory/Ownership_in_Rust.md
    - blog/Rust_memory/Stack_and_heap.md
    - blog/Rust_memory/Borrow_and_Reference_in_Rust.md
  - LeetCode 206:
    - blog/leetcode_206/LeetCode_206_is_my_fav.md
    - blog/leetcode_206/No.1 MokuHazushi.md
    - blog/leetcode_206/What_on_earth_is_if_let_Some(x)=&x{}.md
  - Rust Misc:
    - blog/Rust_Misc/Rust_Box.md