site_name: Ezio's blog
repo_url: https://github.com/CLQuantizer/ezblog
extra_css:
  - stylesheets/extra.css

theme:
    logo: assets/logo.png
    name: material
    palette:
      # Palette toggle for light mode
      - scheme: default
        toggle:
          icon: material/brightness-7 
          name: Switch to dark mode

      # Palette toggle for dark mode
      - scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode

nav:
  - index.md
  - blog/posts/Rust.md
  - blog/posts/core_dump.md

plugins:
  - blog:
      post_url_date_format: yyyy/MM/dd

      
      

