site_name: whatever works

repo_url: https://github.com/CLQuantizer/eztech
extra_css:
  - stylesheets/extra.css

theme:
    name: material
    palette:
      primary: pink

plugins:
  - blog

nav:
  - Blog:
    - blog/index.md 
