site_name: whatever works
# site_url: https://example.com
site_favicon: icon.ico
nav:
    - Home: index.md
    - Scriptum: scriptum.md
    # - About: about.md

theme: readthedocs
extra_css: [extra.css]
repo_url: https://github.com/CLQuantizer/eztech
