site_name: eztech
# site_url: https://example.com
nav:
    - Home: index.md
    - Scriptum: scriptum.md
    # - About: about.md

theme: readthedocs
extra_css: [extra.css]
theme_dir: custom_theme
site_favicon: icon.ico